coin_spark:
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-master
      port: 10001 
      schema: coingecko
      threads: "{{ env_var('DBT_THREADS', 4) }}"
      use_ssl: false
  target: dev