services:
  # -----------------------------
  # Spark Master
  # -----------------------------
  spark-master:
    stdin_open: true
    tty: true
    build:
      context: ../..
      dockerfile: ./docker/spark/local/Dockerfile
    container_name: spark-master
    entrypoint: /bin/sh
    env_file:
      - ../../env/.env_dev
    ports:
      - 10001:10001
      - 8080:8080
    volumes:
      - ../../dbt/coin_spark:/var/lib/spark/coin_spark
      - ../../dbt/profiles.yml:/var/lib/spark/.dbt/profiles.yml
      - ../../docker/spark/spark-utils/start-thrift-server.sh:/spark_utils/start-thrift-server.sh
      - ../../docker/spark/spark-utils/hive-site.xml:/etc/spark/conf/hive-site.xml
    networks:
      - langfuse-network

  # -----------------------------
  # Langgraph Backend
  # -----------------------------
  langgraph-backend:
    stdin_open: true
    tty: true
    build:
      context: ../..
      dockerfile: ./docker/langgraph/Dockerfile
    entrypoint: /bin/sh
    ports:
      - "7860:7860"
    volumes:
      - ../../docker/langgraph/app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../dbt/coin_spark:/dbt/coin_spark
      - ../../dbt/profiles.yml:/dbt/profiles/profiles.yml
    environment:
      DBT_PROJECT_PATH: /dbt/coin_spark
      DBT_PROFILES_DIR: /dbt/profiles
      DBT_TARGET: dev-mcp-server
      # Langfuse Integration
      LANGFUSE_PUBLIC_KEY: pk-lf-329cba82-2726-468e-aaed-3bbaaa5d39ea
      LANGFUSE_SECRET_KEY: sk-lf-771fd06e-17ce-4d00-a0df-006808b46e0c
      LANGFUSE_HOST: http://langfuse-web:3000
    networks:
      - langfuse-network

networks:
  langfuse-network:
    external: true
