# =========================
# CONFIG
# =========================
.ONESHELL:
SHELL := /bin/bash

# --- Images / ECR ---
IMAGE_NAME    = coingecko-ingest
AWS_REGION   ?= us-east-1
ACCOUNT_ID   := $(shell aws sts get-caller-identity --query "Account" --output text)
REPO_URI     := $(ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(IMAGE_NAME)
TAG          ?= latest
FUNCTION_NAME = coingecko_snapshot_ingest

# --- Paths ---
TERRAFORM_DIR  ?= deployment
LAMBDA_DIR      = $(TERRAFORM_DIR)/lambda_ingest_container
COMPOSE_FILE    = docker/spark/docker-compose.yml

# --- App / DBT ---
DBT_DIR     := coindbt
MODELS_DIR  := $(DBT_DIR)/models
VENV_DIR    := venv
ENVIRONMENT ?= dev
export DBT_PROFILES_DIR := $(realpath $(DBT_DIR))

# --- Make-time env files ---
env_file_path  = env/.env_dev
infra_env_file = env/.env_infra

# Load envs (dev first; infra after TF runs)
-include $(env_file_path)
-include $(infra_env_file)
export

# --- LangGraph Image / ECR (built from docker/langgraph/Dockerfile) ---
LANGGRAPH_IMAGE_NAME ?= news-ingest-langgraph
LANGGRAPH_DIR        ?= docker/langgraph
LANGGRAPH_TAG        ?= latest

# If Terraform exports this, we prefer it (see terraform-env below)
# Fallback: compute the repo URI as <acct>.dkr.ecr.<region>.amazonaws.com/<name>
LANGGRAPH_ECR_URL    ?= $(ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(LANGGRAPH_IMAGE_NAME)

.PHONY: login-langgraph buildimage-langgraph tag-langgraph push-langgraph

login-langgraph:
	@echo "🔐 ECR login (LangGraph)…"
	@aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(LANGGRAPH_ECR_URL)

buildimage-langgraph:
	@echo "🐳 Building LangGraph image (linux/amd64)…"
	docker build --platform linux/amd64 --provenance=false -t $(LANGGRAPH_IMAGE_NAME) -f $(LANGGRAPH_DIR)/Dockerfile .

tag-langgraph:
	@echo "🔖 Tagging LangGraph image…"
	docker tag $(LANGGRAPH_IMAGE_NAME):latest $(LANGGRAPH_ECR_URL):$(LANGGRAPH_TAG)

push-langgraph: login-langgraph buildimage-langgraph tag-langgraph
	@echo "🚀 Pushing LangGraph image to ECR…"
	docker push $(LANGGRAPH_ECR_URL):$(LANGGRAPH_TAG)

# =========================
# PHONY
# =========================
.PHONY: help \
        login buildimage tag push \
        terraform-init terraform-plan terraform-apply terraform-env print-tf-outputs \
        deploy update-lambda clean \
        compose-build-spark-dbt compose-up-spark-dbt compose-down-spark-dbt \
        compose-run-spark-dbt compose-run-langgraph \
        verify-market-env \
        setup-env install-requirements run download \
        generate-semantics generate-denorm generate-denorm-all-coins generate-all-coins-metrics \
        dbt-deps dbt-run dbt-docs test_agents all

# =========================
# HELP
# =========================
help:
	@echo "Infra:"
	@echo "  push, terraform-apply, terraform-env, deploy, update-lambda, print-tf-outputs"
	@echo "Containers:"
	@echo "  compose-up-spark-dbt, compose-run-spark-dbt, compose-run-langgraph, compose-down-spark-dbt"
	@echo "DBT & utils:"
	@echo "  download, generate-denorm, generate-denorm-all-coins, generate-semantics, generate-all-coins-metrics, dbt-run, dbt-docs, all"
	@echo "Validation:"
	@echo "  verify-market-env  # checks required env vars for market tools"

# =========================
# ECR AUTH / BUILD / PUSH
# =========================
login:
	@echo "🔐 Logging in to ECR..."
	@aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(REPO_URI)

buildimage:
	@echo "🐳 Building Docker image for Lambda (linux/amd64)…"
	docker build --platform linux/amd64 --provenance=false -t $(IMAGE_NAME) $(LAMBDA_DIR)

tag:
	@echo "🔖 Tagging image…"
	docker tag $(IMAGE_NAME):latest $(REPO_URI):$(TAG)

push: login buildimage tag
	@echo "🚀 Pushing image to ECR…"
	docker push $(REPO_URI):$(TAG)

# =========================
# TERRAFORM (Aurora/pgvector KB + S3 DS)
# =========================
terraform-init:
	cd $(TERRAFORM_DIR) && terraform init

terraform-plan: terraform-init
	@set -a; . $(env_file_path); set +a; \
	cd $(TERRAFORM_DIR) && terraform plan 

terraform-apply: terraform-init
	@set -e; \
	set -a; . $(env_file_path); set +a; \
	cd $(TERRAFORM_DIR) && terraform apply -auto-approve 

# Export TF outputs -> env/.env_infra for runtime:
#   AWS_REGION,
#   NEWS_KB_ID, NEWS_KB_DS_ID, NEWS_KB_BUCKET, NEWS_KB_PREFIX,
#   RESEARCH_KB_ID,
#   AURORA_CLUSTER_ARN, AURORA_SECRET_ARN, AURORA_DB_NAME, RESEARCH_TABLE
terraform-env:
	@set -e; \
	mkdir -p $$(dirname $(infra_env_file)); \
	{ \
	  echo "# generated by make terraform-env"; \
	  echo "AWS_REGION=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw aws_region)"; \
	  echo "NEWS_KB_ID=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_id)"; \
	  echo "NEWS_KB_DS_ID=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_data_source_id)"; \
	  echo "NEWS_KB_BUCKET=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_bucket)"; \
	  echo "NEWS_KB_PREFIX=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_prefix)"; \
	  echo "RESEARCH_KB_ID=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw research_kb_id)"; \
	  echo "RESEARCH_KB_DS_ID=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw research_kb_data_source_id)"; \
	  echo "RESEARCH_KB_BUCKET=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw research_kb_bucket)"; \
	  echo "AURORA_CLUSTER_ARN=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw aurora_cluster_arn)"; \
	  echo "AURORA_SECRET_ARN=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw aurora_secret_arn)"; \
	  echo "AURORA_DB_NAME=$$({ terraform -chdir=$(TERRAFORM_DIR) output -raw aurora_db_name 2>/dev/null || echo kbdb; })"; \
	  echo "RESEARCH_TABLE=$$({ terraform -chdir=$(TERRAFORM_DIR) output -raw research_table_name 2>/dev/null || echo public.research_kb; })"; \
	  echo "NEWS_TABLE=$$({ terraform -chdir=$(TERRAFORM_DIR) output -raw news_table_name 2>/dev/null || echo public.news_kb; })"; \
	} > $(infra_env_file); \
	echo "✅ Wrote $(infra_env_file)"

print-tf-outputs:
	@echo "aws_region               : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw aws_region)"
	@echo "news_kb_id               : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_id)"
	@echo "news_kb_data_source_id   : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_data_source_id)"
	@echo "news_kb_bucket           : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_bucket)"
	@echo "news_kb_prefix           : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_prefix)"
	@echo "research_kb_id           : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw research_kb_id)"
	@echo "research_kb_data_source_id   : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw research_kb_data_source_id)"
	@echo "research_kb_bucket           : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw research_kb_bucket)"
	@echo "aurora_cluster_arn       : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw aurora_cluster_arn)"
	@echo "aurora_secret_arn        : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw aurora_secret_arn)"
	@echo "aurora_db_name           : $$({ terraform -chdir=$(TERRAFORM_DIR) output -raw aurora_db_name 2>/dev/null || echo kbdb; })"
	@echo "research_table_name      : $$({ terraform -chdir=$(TERRAFORM_DIR) output -raw research_table_name 2>/dev/null || echo public.research_kb; })"
	@echo "news_table_name          : $$({ terraform -chdir=$(TERRAFORM_DIR) output -raw news_table_name 2>/dev/null || echo public.news_kb; })"

deploy: push terraform-apply terraform-env
	@echo "✅ Deployment complete."

update-lambda:
	aws lambda update-function-code \
		--function-name $(FUNCTION_NAME) \
		--image-uri $(REPO_URI):$(TAG)
	@echo "♻️ Lambda function updated with latest image."

clean:
	docker rmi $(IMAGE_NAME):latest || true
	docker rmi $(REPO_URI):$(TAG) || true

# =========================
# VALIDATION (market tools env)
# =========================
verify-market-env:
	@set -e; \
	. $(env_file_path); test -f $(infra_env_file) && . $(infra_env_file) || true; \
	for v in AWS_REGION NEWS_KB_ID NEWS_KB_BUCKET NEWS_KB_PREFIX RESEARCH_KB_ID AURORA_CLUSTER_ARN AURORA_SECRET_ARN AURORA_DB_NAME RESEARCH_TABLE; do \
	  val=$$(eval echo \$$$${v}); \
	  if [ -z "$${val}" ]; then echo "❌ Missing $$v"; MISSING=1; fi; \
	done; \
	if [ "$${MISSING:-0}" = "1" ]; then exit 1; fi; \
	echo "✅ Market tools env looks good."

# =========================
# DOCKER COMPOSE (wired to Terraform/env)
# =========================
compose-build-spark-dbt:
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose \
		-f $(COMPOSE_FILE) build \
		--build-arg ENVIRONMENT="$(ENVIRONMENT)" --parallel

compose-up-spark-dbt: terraform-apply terraform-env #compose-build-spark-dbt
	docker-compose -f $(COMPOSE_FILE) up --always-recreate-deps -d

compose-down-spark-dbt:
	docker-compose -f $(COMPOSE_FILE) down

compose-run-spark-dbt: compose-up-spark-dbt
	. $(env_file_path); . $(infra_env_file); \
	docker-compose -f $(COMPOSE_FILE) exec \
        -e AWS_ACCESS_KEY_ID="$$AWS_ACCESS_KEY_ID" \
        -e AWS_SECRET_ACCESS_KEY="$$AWS_SECRET_ACCESS_KEY" \
        -e AWS_SESSION_TOKEN="$$AWS_SESSION_TOKEN" \
        -e AWS_REGION="$$AWS_REGION" \
        -e NEWS_KB_ID="$$NEWS_KB_ID" \
        -e NEWS_KB_DS_ID="$$NEWS_KB_DS_ID" \
        -e NEWS_KB_BUCKET="$$NEWS_KB_BUCKET" \
        -e NEWS_KB_PREFIX="$$NEWS_KB_PREFIX" \
        -e RESEARCH_KB_ID="$$RESEARCH_KB_ID" \
        -e AURORA_CLUSTER_ARN="$$AURORA_CLUSTER_ARN" \
        -e AURORA_SECRET_ARN="$$AURORA_SECRET_ARN" \
        -e AURORA_DB_NAME="$$AURORA_DB_NAME" \
        -e RESEARCH_TABLE="$$RESEARCH_TABLE" \
        spark-master \
		/bin/bash -c "/spark_utils/start-thrift-server.sh && /bin/bash"

compose-run-langgraph: compose-up-spark-dbt
	. $(env_file_path); . $(infra_env_file); \
	docker-compose -f $(COMPOSE_FILE) exec \
        -e AWS_ACCESS_KEY_ID="$$AWS_ACCESS_KEY_ID" \
        -e AWS_SECRET_ACCESS_KEY="$$AWS_SECRET_ACCESS_KEY" \
        -e AWS_SESSION_TOKEN="$$AWS_SESSION_TOKEN" \
        -e AWS_REGION="$$AWS_REGION" \
        -e NEWS_KB_ID="$$NEWS_KB_ID" \
        -e NEWS_KB_DS_ID="$$NEWS_KB_DS_ID" \
        -e NEWS_KB_BUCKET="$$NEWS_KB_BUCKET" \
        -e NEWS_KB_PREFIX="$$NEWS_KB_PREFIX" \
        -e RESEARCH_KB_ID="$$RESEARCH_KB_ID" \
		-e RESEARCH_KB_DS_ID="$$RESEARCH_KB_DS_ID" \
		-e RESEARCH_KB_PREFIX="$$RESEARCH_KB_PREFIX" \
        -e AURORA_CLUSTER_ARN="$$AURORA_CLUSTER_ARN" \
        -e AURORA_SECRET_ARN="$$AURORA_SECRET_ARN" \
        -e AURORA_DB_NAME="$$AURORA_DB_NAME" \
        -e RESEARCH_TABLE="$$RESEARCH_TABLE" \
        langgraph-backend \
        /bin/bash



.PHONY: clean-iceberg-news clean-aurora-research clean-aurora-news reset-data

# --- Athena defaults (override if needed) ---
ATHENA_WORKGROUP   ?= primary
ATHENA_OUTPUT_S3   ?= s3://$(NEWS_KB_BUCKET)/athena-results
ICEBERG_DB         ?= news_agent
ICEBERG_NEWS_TABLE ?= cryptoapi_news

# Safety prompt (set CONFIRM=yes to skip)
CONFIRM ?= no

clean-iceberg-news:
	@set -euo pipefail
	@TGT="$(ICEBERG_DB).$(ICEBERG_NEWS_TABLE) (Iceberg via Athena)"; \
	if [ "$(CONFIRM)" != "yes" ]; then \
	  read -p "This will DELETE ALL ROWS in $$TGT. Continue? [y/N] " ans; \
	  case $$ans in y|Y) ;; *) echo "Aborted."; exit 1;; esac; \
	fi; \
	if [ -z "$(ICEBERG_DB)" ] || [ -z "$(ICEBERG_NEWS_TABLE)" ]; then echo "❌ ICEBERG_DB/ICEBERG_NEWS_TABLE not set"; exit 1; fi; \
	SQL="DELETE FROM $(ICEBERG_DB).$(ICEBERG_NEWS_TABLE) WHERE 1=1"; \
	echo "▶ Submitting Athena query (workgroup: $(ATHENA_WORKGROUP)):"; \
	echo "   $$SQL"; \
	# Try WITHOUT ResultConfiguration (works when Managed Query Results are enabled) \
	set +e; \
	QID=$$(aws athena start-query-execution \
	  --work-group "$(ATHENA_WORKGROUP)" \
	  --query-string "$$SQL" \
	  --query 'QueryExecutionId' --output text 2>/dev/null); \
	RC=$$?; set -e; \
	if [ $$RC -ne 0 ] || [ -z "$$QID" ]; then \
	  if [ -z "${ATHENA_OUTPUT_S3:-}" ]; then \
	    echo "⚠️  Managed results failed and ATHENA_OUTPUT_S3 is not set. Set ATHENA_OUTPUT_S3 or configure workgroup results."; \
	    exit 1; \
	  fi; \
	  echo "ℹ️  Retrying with explicit --result-configuration → $(ATHENA_OUTPUT_S3)"; \
	  QID=$$(aws athena start-query-execution \
	    --work-group "$(ATHENA_WORKGROUP)" \
	    --query-string "$$SQL" \
	    --result-configuration "OutputLocation=$(ATHENA_OUTPUT_S3)" \
	    --query 'QueryExecutionId' --output text); \
	fi; \
	if [ -z "$$QID" ]; then echo "❌ Failed to start Athena query."; exit 1; fi; \
	echo "   QueryExecutionId: $$QID"; \
	while true; do \
	  STATE=$$(aws athena get-query-execution --query-execution-id "$$QID" \
	    --query 'QueryExecution.Status.State' --output text); \
	  case "$$STATE" in \
	    SUCCEEDED) echo "✅ Iceberg table cleared."; break;; \
	    FAILED|CANCELLED) \
	      echo "❌ Athena query $$STATE"; \
	      aws athena get-query-execution --query-execution-id "$$QID" \
	        --query 'QueryExecution.Status.StateChangeReason' --output text; \
	      exit 1;; \
	    *) echo "⏳ $$STATE ..."; sleep 3;; \
	  esac; \
	done

clean-aurora-research:
	@set -euo pipefail
	@TGT="$(RESEARCH_TABLE) (Aurora Postgres)"; \
	if [ "$(CONFIRM)" != "yes" ]; then \
	  read -p "This will DELETE ALL ROWS in $$TGT. Continue? [y/N] " ans; \
	  case $$ans in y|Y) ;; *) echo "Aborted."; exit 1;; esac; \
	fi; \
	if [ -z "$(AURORA_CLUSTER_ARN)" ] || [ -z "$(AURORA_SECRET_ARN)" ] || [ -z "$(AURORA_DB_NAME)" ]; then \
	  echo "❌ Missing Aurora env (AURORA_CLUSTER_ARN / AURORA_SECRET_ARN / AURORA_DB_NAME)"; exit 1; fi; \
	if [ -z "$(RESEARCH_TABLE)" ]; then echo "❌ RESEARCH_TABLE is empty"; exit 1; fi; \
	echo "▶ Deleting from $(RESEARCH_TABLE) ..."; \
	aws rds-data execute-statement \
	  --resource-arn "$(AURORA_CLUSTER_ARN)" \
	  --secret-arn   "$(AURORA_SECRET_ARN)" \
	  --database     "$(AURORA_DB_NAME)" \
	  --sql "DELETE FROM $(RESEARCH_TABLE);"; \
	echo "✅ Aurora research table cleared."

# Optional: set NEWS_TABLE (e.g., public.news_kb) to enable this
clean-aurora-news:
	@set -euo pipefail; \
	if [ -z "$(NEWS_TABLE)" ]; then \
	  echo "ℹ️  NEWS_TABLE not set; skipping Aurora news delete."; \
	else \
	  TGT="$(NEWS_TABLE) (Aurora Postgres)"; \
	  if [ "$(CONFIRM)" != "yes" ]; then \
	    read -p "This will DELETE ALL ROWS in $$TGT. Continue? [y/N] " ans; \
	    case $$ans in y|Y) ;; *) echo "Aborted."; exit 1;; esac; \
	  fi; \
	  if [ -z "$(AURORA_CLUSTER_ARN)" ] || [ -z "$(AURORA_SECRET_ARN)" ] || [ -z "$(AURORA_DB_NAME)" ]; then \
	    echo "❌ Missing Aurora env (AURORA_CLUSTER_ARN / AURORA_SECRET_ARN / AURORA_DB_NAME)"; exit 1; \
	  fi; \
	  echo "▶ Deleting from $(NEWS_TABLE) ..."; \
	  aws rds-data execute-statement \
	    --resource-arn "$(AURORA_CLUSTER_ARN)" \
	    --secret-arn   "$(AURORA_SECRET_ARN)" \
	    --database     "$(AURORA_DB_NAME)" \
	    --sql "DELETE FROM $(NEWS_TABLE);"; \
	  echo "✅ Aurora news table cleared."; \
	fi

reset-data: clean-iceberg-news clean-aurora-research clean-aurora-news
	@echo "🌱 Done. You’re back to a clean slate."

# =========================
# S3 cleanup for Bedrock KB source
# =========================
# Env expected:
#   NEWS_KB_BUCKET   (e.g., jj-news-kb)
#   NEWS_KB_PREFIX   (e.g., news)  # don't include leading slash
# Optional:
#   CONFIRM=yes      # skip interactive prompt
#   DRYRUN=yes       # preview only
#   DT=YYYY-MM-DD    # for partitioned paths news/dt=YYYY-MM-DD/
#   BEFORE_ISO=YYYY-MM-DDTHH:MM:SSZ  # delete keys last-modified on/before this timestamp
#
# Notes:
# - Deleting S3 objects removes them from the KB on the next ingestion sync.
# - If you haven’t partitioned yet, use clean-kb-s3 (everything under prefix).
# - If you *have* partitioned by date (news/dt=YYYY-MM-DD/), use clean-kb-s3-dt.

.PHONY: clean-kb-s3 clean-kb-s3-dt clean-kb-s3-before list-kb-s3

list-kb-s3:
	@set -euo pipefail; \
	if [ -z "$(NEWS_KB_BUCKET)" ]; then echo "❌ NEWS_KB_BUCKET not set"; exit 1; fi; \
	PFX="$${NEWS_KB_PREFIX:-news}"; PFX="$${PFX%/}"; \
	echo "▶ Counting objects under s3://$(NEWS_KB_BUCKET)/$${PFX}/ ..."; \
	aws s3api list-objects-v2 --bucket "$(NEWS_KB_BUCKET)" --prefix "$${PFX}/" \
	  --query "length(Contents)" --output text

clean-kb-s3:
	@set -euo pipefail; \
	if [ -z "$(NEWS_KB_BUCKET)" ]; then echo "❌ NEWS_KB_BUCKET not set"; exit 1; fi; \
	PFX="$${NEWS_KB_PREFIX:-news}"; PFX="$${PFX%/}"; \
	TGT="s3://$(NEWS_KB_BUCKET)/$${PFX}/"; \
	if [ "$(CONFIRM)" != "yes" ]; then \
	  read -p "This will DELETE ALL objects under $$TGT. Continue? [y/N] " ans; \
	  case $$ans in y|Y) ;; *) echo "Aborted."; exit 1;; esac; \
	fi; \
	if [ "$${DRYRUN:-no}" = "yes" ]; then DR="--dryrun"; else DR=""; fi; \
	echo "▶ Deleting $$TGT $$DR"; \
	aws s3 rm "$$TGT" --recursive $$DR; \
	echo "✅ S3 prefix cleared (or dry-run)."

# Use this if you store docs under news/dt=YYYY-MM-DD/<id>.txt (+ .metadata.json)
clean-kb-s3-dt:
	@set -euo pipefail; \
	if [ -z "$(NEWS_KB_BUCKET)" ]; then echo "❌ NEWS_KB_BUCKET not set"; exit 1; fi; \
	if [ -z "${DT:-}" ]; then echo "❌ Set DT=YYYY-MM-DD"; exit 1; fi; \
	PFX="$${NEWS_KB_PREFIX:-news}"; PFX="$${PFX%/}"; \
	TGT="s3://$(NEWS_KB_BUCKET)/$${PFX}/dt=$(DT)/"; \
	if [ "$(CONFIRM)" != "yes" ]; then \
	  read -p "This will DELETE ALL objects under $$TGT. Continue? [y/N] " ans; \
	  case $$ans in y|Y) ;; *) echo "Aborted."; exit 1;; esac; \
	fi; \
	if [ "$${DRYRUN:-no}" = "yes" ]; then DR="--dryrun"; else DR=""; fi; \
	echo "▶ Deleting $$TGT $$DR"; \
	aws s3 rm "$$TGT" --recursive $$DR; \
	echo "✅ Partition $$TGT cleared (or dry-run)."

# Delete only objects last-modified on/before BEFORE_ISO (requires jq)
clean-kb-s3-before:
	@set -euo pipefail; \
	if [ -z "$(NEWS_KB_BUCKET)" ]; then echo "❌ NEWS_KB_BUCKET not set"; exit 1; fi; \
	if [ -z "${BEFORE_ISO:-}" ]; then echo "❌ Set BEFORE_ISO=YYYY-MM-DDTHH:MM:SSZ"; exit 1; fi; \
	if ! command -v jq >/dev/null 2>&1; then echo "❌ Requires jq"; exit 1; fi; \
	PFX="$${NEWS_KB_PREFIX:-news}"; PFX="$${PFX%/}"; \
	echo "▶ Selecting objects under s3://$(NEWS_KB_BUCKET)/$${PFX}/ with LastModified <= $(BEFORE_ISO)"; \
	KEYS=$$(aws s3api list-objects-v2 --bucket "$(NEWS_KB_BUCKET)" --prefix "$${PFX}/" \
	  --query "Contents[?LastModified<=\`$(BEFORE_ISO)\`].Key" --output json); \
	COUNT=$$(echo "$$KEYS" | jq 'length'); \
	echo "Found $$COUNT objects."; \
	if [ "$$COUNT" -eq 0 ]; then exit 0; fi; \
	if [ "$(CONFIRM)" != "yes" ]; then \
	  read -p "Proceed to delete $$COUNT objects? [y/N] " ans; \
	  case $$ans in y|Y) ;; *) echo "Aborted."; exit 1;; esac; \
	fi; \
	if [ "$${DRYRUN:-no}" = "yes" ]; then \
	  echo "$$KEYS" | jq -r '.[]'; echo "DRYRUN=yes → not deleting."; exit 0; \
	fi; \
	TMP=$$(mktemp); echo "$$KEYS" | jq -c '{Objects: map({Key:.}), Quiet:true}' > $$TMP; \
	aws s3api delete-objects --bucket "$(NEWS_KB_BUCKET)" --delete file://$$TMP; \
	rm -f $$TMP; \
	echo "✅ Deleted $$COUNT objects."

