# =========================
# CONFIG
# =========================
.ONESHELL:
SHELL := /bin/bash

# --- Images / ECR ---
IMAGE_NAME    = coingecko-ingest
AWS_REGION   ?= us-east-1
ACCOUNT_ID   := $(shell aws sts get-caller-identity --query "Account" --output text)
REPO_URI     := $(ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(IMAGE_NAME)
TAG          ?= latest
FUNCTION_NAME = coingecko_snapshot_ingest

# --- Paths ---
TERRAFORM_DIR  ?= deployment
LAMBDA_DIR      = $(TERRAFORM_DIR)/lambda_ingest_container
COMPOSE_FILE    = docker/spark/docker-compose.yml

# --- App / DBT ---
DBT_DIR     := coindbt
MODELS_DIR  := $(DBT_DIR)/models
VENV_DIR    := venv
ENVIRONMENT ?= dev
export DBT_PROFILES_DIR := $(realpath $(DBT_DIR))

# --- Make-time env files ---
env_file_path  = env/.env_dev
infra_env_file = env/.env_infra

# Load envs (dev first; infra after TF runs)
-include $(env_file_path)
-include $(infra_env_file)
export

# =========================
# PHONY
# =========================
.PHONY: help \
        login buildimage tag push \
        terraform-init terraform-plan terraform-apply terraform-env print-tf-outputs \
        deploy update-lambda clean \
        compose-build-spark-dbt compose-up-spark-dbt compose-down-spark-dbt \
        compose-run-spark-dbt compose-run-langgraph \
        setup-env install-requirements run download \
        generate-semantics generate-denorm generate-denorm-all-coins generate-all-coins-metrics \
        dbt-deps dbt-run dbt-docs test_agents all

# =========================
# HELP
# =========================
help:
	@echo "Infra:"
	@echo "  push, terraform-apply, terraform-env, deploy, update-lambda, print-tf-outputs"
	@echo "Containers:"
	@echo "  compose-up-spark-dbt, compose-run-spark-dbt, compose-run-langgraph, compose-down-spark-dbt"
	@echo "DBT & utils:"
	@echo "  download, generate-denorm, generate-denorm-all-coins, generate-semantics, generate-all-coins-metrics, dbt-run, dbt-docs, all"

# =========================
# ECR AUTH / BUILD / PUSH
# =========================
login:
	@echo "🔐 Logging in to ECR..."
	@aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(REPO_URI)

buildimage:
	@echo "🐳 Building Docker image for Lambda (linux/amd64)…"
	docker build --platform linux/amd64 --provenance=false -t $(IMAGE_NAME) $(LAMBDA_DIR)

tag:
	@echo "🔖 Tagging image…"
	docker tag $(IMAGE_NAME):latest $(REPO_URI):$(TAG)

push: login buildimage tag
	@echo "🚀 Pushing image to ECR…"
	docker push $(REPO_URI):$(TAG)

# =========================
# TERRAFORM (Aurora/pgvector KB + S3 DS)
# =========================
terraform-init:
	cd $(TERRAFORM_DIR) && terraform init

terraform-plan: terraform-init
	@set -a; . $(env_file_path); set +a; \
	cd $(TERRAFORM_DIR) && terraform plan \
	  -var="ingestion_image=$(IMAGE_NAME)"

terraform-apply: terraform-init
	@set -e; \
	set -a; . $(env_file_path); set +a; \
	cd $(TERRAFORM_DIR) && terraform apply -auto-approve \
	  -var="ingestion_image=$(IMAGE_NAME)"

# Export TF outputs -> env/.env_infra for runtime:
#   AWS_REGION, NEWS_KB_ID, NEWS_KB_DS_ID, NEWS_KB_BUCKET, NEWS_KB_PREFIX
terraform-env:
	@set -e; \
	mkdir -p $$(dirname $(infra_env_file)); \
	{ \
	  echo "# generated by make terraform-env"; \
	  echo "AWS_REGION=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw aws_region)"; \
	  echo "NEWS_KB_ID=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_id)"; \
	  echo "NEWS_KB_DS_ID=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_data_source_id)"; \
	  echo "NEWS_KB_BUCKET=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_bucket)"; \
	  echo "NEWS_KB_PREFIX=$$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_prefix)"; \
	} > $(infra_env_file); \
	echo "✅ Wrote $(infra_env_file)"

print-tf-outputs:
	@echo "aws_region             : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw aws_region)"
	@echo "news_kb_id             : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_id)"
	@echo "news_kb_data_source_id : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_data_source_id)"
	@echo "news_kb_bucket         : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_bucket)"
	@echo "news_kb_prefix         : $$(terraform -chdir=$(TERRAFORM_DIR) output -raw news_kb_prefix)"

deploy: push terraform-apply terraform-env
	@echo "✅ Deployment complete."

update-lambda:
	aws lambda update-function-code \
		--function-name $(FUNCTION_NAME) \
		--image-uri $(REPO_URI):$(TAG)
	@echo "♻️ Lambda function updated with latest image."

clean:
	docker rmi $(IMAGE_NAME):latest || true
	docker rmi $(REPO_URI):$(TAG) || true

# =========================
# DOCKER COMPOSE (wired to Terraform/env)
# =========================
compose-build-spark-dbt:
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose \
		-f $(COMPOSE_FILE) build \
		--build-arg ENVIRONMENT="$(ENVIRONMENT)" --parallel

compose-up-spark-dbt: terraform-apply terraform-env compose-build-spark-dbt
	docker-compose -f $(COMPOSE_FILE) up --always-recreate-deps -d

compose-down-spark-dbt:
	docker-compose -f $(COMPOSE_FILE) down

compose-run-spark-dbt: compose-up-spark-dbt
	. $(env_file_path); . $(infra_env_file); \
	docker-compose -f $(COMPOSE_FILE) exec \
        -e AWS_ACCESS_KEY_ID="$$AWS_ACCESS_KEY_ID" \
        -e AWS_SECRET_ACCESS_KEY="$$AWS_SECRET_ACCESS_KEY" \
        -e AWS_SESSION_TOKEN="$$AWS_SESSION_TOKEN" \
        -e AWS_REGION="$$AWS_REGION" \
        -e NEWS_KB_ID="$$NEWS_KB_ID" \
        -e NEWS_KB_DS_ID="$$NEWS_KB_DS_ID" \
        -e NEWS_KB_BUCKET="$$NEWS_KB_BUCKET" \
        -e NEWS_KB_PREFIX="$$NEWS_KB_PREFIX" \
        spark-master \
		/bin/bash -c "/spark_utils/start-thrift-server.sh && /bin/bash"

compose-run-langgraph: compose-up-spark-dbt
	. $(env_file_path); . $(infra_env_file); \
	docker-compose -f $(COMPOSE_FILE) exec \
        -e AWS_ACCESS_KEY_ID="$$AWS_ACCESS_KEY_ID" \
        -e AWS_SECRET_ACCESS_KEY="$$AWS_SECRET_ACCESS_KEY" \
        -e AWS_SESSION_TOKEN="$$AWS_SESSION_TOKEN" \
        -e AWS_REGION="$$AWS_REGION" \
        -e NEWS_KB_ID="$$NEWS_KB_ID" \
        -e NEWS_KB_DS_ID="$$NEWS_KB_DS_ID" \
        -e NEWS_KB_BUCKET="$$NEWS_KB_BUCKET" \
        -e NEWS_KB_PREFIX="$$NEWS_KB_PREFIX" \
        langgraph-backend \
        /bin/bash

# =========================
# PYTHON / DBT (unchanged logic)
# =========================
COINS := $(if $(COINS),$(COINS),bitcoin)
SAFE_COIN_LIST := $(shell echo $(COINS) | tr ',' ' ' | sed 's/\.sql//g' | sed 's/-/_/g')
COIN_NAMES := $(shell ls $(MODELS_DIR)/denorm_*_history.sql 2>/dev/null | sed -E "s|.*/denorm_(.*)_history\.sql$$|\1|")
SEMANTIC_TARGETS := $(patsubst %, $(MODELS_DIR)/%_semantic.yml, $(SAFE_COIN_LIST))

setup-env: $(VENV_DIR)/bin/activate

$(VENV_DIR)/bin/activate: requirements.txt
	@echo "Creating virtual environment in $(VENV_DIR)…"
	python3 -m venv $(VENV_DIR)
	@echo "Virtual environment created."
	@echo "Installing dependencies…"
	./$(VENV_DIR)/bin/pip install --upgrade pip
	./$(VENV_DIR)/bin/pip install -r requirements.txt
	touch $(VENV_DIR)/bin/activate

install-requirements: setup-env

run: setup-env
	./$(VENV_DIR)/bin/python fetch_coin_history.py --coins $(COINS)

generate-semantics: setup-env $(SEMANTIC_TARGETS)
	@echo "All semantic files generated/overwritten."

$(MODELS_DIR)/%_semantic.yml: $(MODELS_DIR)/denorm_%_history.sql semantic_template.yml
	@echo "Generating semantic file for coin: $*"
	mkdir -p $(MODELS_DIR)
	sed 's/{{COIN}}/$*/g' semantic_template.yml > $@
	@echo "Created/overwritten $@ from template."

DENORM_TARGETS := $(patsubst %, $(MODELS_DIR)/denorm_%_history.sql, $(SAFE_COIN_LIST))

generate-denorm: setup-env $(DENORM_TARGETS)
	@echo "All per-coin denormalized model files generated/overwritten."

$(MODELS_DIR)/denorm_%_history.sql: denorm_template.sql
	@echo "Generating denorm file for coin: $*"
	mkdir -p $(MODELS_DIR)
	safe_coin=$$(echo "$*" | sed 's/-/_/g'); \
	sed "s/{{COIN}}/$$safe_coin/g" denorm_template.sql > $@
	@echo "Created/overwritten $@ from template."

generate-denorm-all-coins: setup-env $(MODELS_DIR)/denorm_all_coins.sql
	@echo "Master denormalized model for all coins generated/overwritten."

$(MODELS_DIR)/denorm_all_coins.sql: master_coin_denorm.sql
	@echo "Generating master denormalized model from template…"
	mkdir -p $(MODELS_DIR)
	@COIN_UNION=$$(for coin in $(SAFE_COIN_LIST); do \
		echo "select *, '$${coin}' as coin from $${coin}_history"; \
	done | paste -sd " UNION ALL " -); \
	echo "COIN_UNION is: $$COIN_UNION"; \
	sed -e "s|{{COIN_UNION}}|$$COIN_UNION|g" master_coin_denorm.sql > $(MODELS_DIR)/denorm_all_coins.sql; \
	echo "Created/overwritten $(MODELS_DIR)/denorm_all_coins.sql from template."

generate-all-coins-metrics: setup-env $(MODELS_DIR)/all_coins_metrics.yml
	@echo "All coins metrics file generated/overwritten."
$(MODELS_DIR)/all_coins_metrics.yml: render_template.py templates/all_coins_metrics_template.yml
	@echo "Generating all_coins_metrics.yml using render_template.py…"
	./$(VENV_DIR)/bin/python render_template.py

download: setup-env
	@echo "Downloading coin data for coins: $(COINS)…"
	./$(VENV_DIR)/bin/python fetch_coin_history.py --coins $(COINS)

dbt-deps: setup-env
	@echo "Installing dbt packages…"
	@cd $(DBT_DIR) && ../$(VENV_DIR)/bin/dbt deps

dbt-run: dbt-deps
	@echo "Running dbt models…"
	@cd $(DBT_DIR) && \
	if [ -f dbt_project.yml ]; then \
		../$(VENV_DIR)/bin/dbt run --profiles-dir $$DBT_PROFILES_DIR; \
	else \
		echo "Error: No dbt_project.yml found at $(DBT_DIR)/dbt_project.yml"; \
		exit 1; \
	fi

dbt-docs: dbt-deps
	@echo "Generating dbt docs…"
	@cd $(DBT_DIR) && \
	if [ -f dbt_project.yml ]; then \
		../$(VENV_DIR)/bin/dbt docs generate; \
	else \
		echo "Error: No dbt_project.yml found at $(DBT_DIR)/dbt_project.yml"; \
		exit 1; \
	fi

test_agents: setup-env
	PYTHONPATH=$(CURDIR)/coin_crew pytest coin_crew/tests/db

all: download generate-denorm generate-denorm-all-coins generate-semantics generate-all-coins-metrics dbt-run dbt-docs
	@echo "✅ All tasks completed."
